### ISSUE TITLE
Adding devices using network ranges

### ISSUE THREAD

**Issue by hkkris** [arista-netdevops-community/network-test-automation#12]
Hi, 

Wondering if we can have network ranges specified on the devices.txt rather than using unique ip?

Thanks
Hari

**Comment by ksator** [comment]
Using subnets, it should be easy using that approach: 
```
>>> from netaddr import IPNetwork
>>> net=IPNetwork('192.0.2.0/29')
>>> net
IPNetwork('192.0.2.0/29')
>>> type(net)
<class 'netaddr.ip.IPNetwork'>
>>> for ip in net:
...   print(ip)
... 
192.0.2.0
192.0.2.1
192.0.2.2
192.0.2.3
192.0.2.4
192.0.2.5
192.0.2.6
192.0.2.7
>>> net[0]
IPAddress('192.0.2.0')
>>> net[-1]
IPAddress('192.0.2.7')
>>> type(net[0])
<class 'netaddr.ip.IPAddress'>
```
Using ranges, I need to think about it

**Comment by ksator** [comment]
so I will add this feature. If the devices.txt file has a `/` it will be a subnet, if it has a `_` it will be a range, otherwise it will be an IP or hostname.

**Comment by ksator** [comment]
@titom73 
about the example https://github.com/arista-netdevops-community/network-test-automation/blob/master/examples/inventory.yml
could we please use this one (simpler to write for humans): 
```
--- 
anta_inventory: 
  hosts: 
    - host: "192.168.0.17"
    - host: "192.168.0.2"
  networks: 
    - network: 192.168.0.0/24
  ranges: 
    - end: "10.0.0.11"
      start: "10.0.0.1"
    - end: "10.0.0.111"
      start: "10.0.0.100"
```

**Comment by titom73** [comment]
Merged in master branch and available for testing
